In [1]:
import pandas as pd
from IPython.display import display

def format_binary_nibbles(binary_str, num_nibbles=8):
    binary_str = binary_str.zfill(num_nibbles * 4)
    return ' '.join(binary_str[i:i+4] for i in range(0, len(binary_str), 4))

def collatz_sequence_with_operations(n):
    seq = []
    odd_even = []
    operations = []
    growth_strength = []
    collapse_strength = []
    msbs = []
    lsbs = []
    bit_counts = []
    
    iteration_count = 0  # Counter to track the number of iterations
    
    while True:
        iteration_count += 1
        
        binary_n = bin(n)[2:]
        seq.append(n)
        odd_even.append('Even' if n % 2 == 0 else 'Odd')
        msbs.append(format_binary_nibbles(binary_n[:4], num_nibbles=1))
        lsbs.append(format_binary_nibbles(binary_n[-4:], num_nibbles=1))
        bit_counts.append(len(binary_n))
        if n == 1:
            operations.append('')
            growth_strength.append(0)
            collapse_strength.append(0)
            break
        prev_num_bits = len(binary_n)
        if n % 2 == 0:
            shift_count = 0
            while n % 2 == 0:
                n //= 2
                shift_count += 1
            operations.append(f'>> {shift_count}')
            growth_strength.append(0)
            collapse_strength.append(shift_count)
        else:
            n = 3 * n + 1
            operations.append('3x + 1')
            growth_strength.append(len(bin(n)[2:]) - prev_num_bits)
            collapse_strength.append(0)
    
    df = pd.DataFrame({
        'Decimal': seq,
        'Binary': [format_binary_nibbles(bin(num)[2:]) for num in seq],
        'Bit Count': bit_counts,
        'Odd/Even': odd_even,
        'Operation': operations,
        '4 MSBs': msbs,
        'Growth Strength': growth_strength,
        '4 LSBs': lsbs,
        'Collapse Strength': collapse_strength
    })
    
    return df, iteration_count

# Set the display option to show all rows
pd.set_option('display.max_rows', None)

# Specify the binary input
binary_input = "1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110"
binary_input = "1111 1111 1111 1111 1111"

# Remove spaces from the binary input
binary_input = binary_input.replace(" ", "")

# Convert the binary input to decimal
decimal_input = int(binary_input, 2)

# Execute the Collatz sequence for the input number
print(f"Collatz sequence for {binary_input}:")
df, num_iterations = collatz_sequence_with_operations(decimal_input)
display(df)

# Report the number of iterations
print(f"Number of iterations: {num_iterations}")

Collatz sequence for 11111111111111111111:

,Decimal,Binary,Bit Count,Odd/Even,Operation,4 MSBs,Growth Strength,4 LSBs,Collapse Strength
0,1048575,0000 0000 0000 1111 1111 1111 1111 1111,20,Odd,3x + 1,1111,2,1111,0
1,3145726,0000 0000 0010 1111 1111 1111 1111 1110,22,Even,>> 1,1011,0,1110,1
2,1572863,0000 0000 0001 0111 1111 1111 1111 1111,21,Odd,3x + 1,1011,2,1111,0
3,4718590,0000 0000 0100 0111 1111 1111 1111 1110,23,Even,>> 1,1000,0,1110,1
4,2359295,0000 0000 0010 0011 1111 1111 1111 1111,22,Odd,3x + 1,1000,1,1111,0
5,7077886,0000 0000 0110 1011 1111 1111 1111 1110,23,Even,>> 1,1101,0,1110,1
6,3538943,0000 0000 0011 0101 1111 1111 1111 1111,22,Odd,3x + 1,1101,2,1111,0
7,10616830,0000 0000 1010 0001 1111 1111 1111 1110,24,Even,>> 1,1010,0,1110,1
8,5308415,0000 0000 0101 0000 1111 1111 1111 1111,23,Odd,3x + 1,1010,1,1111,0
9,15925246,0000 0000 1111 0010 1111 1111 1111 1110,24,Even,>> 1,1111,0,1110,1
10,7962623,0000 0000 0111 1001 0111 1111 1111 1111,23,Odd,3x + 1,1111,2,1111,0
11,23887870,0000 0001 0110 1100 0111 1111 1111 1110,25,Even,>> 1,1011,0,1110,1
12,11943935,0000 0000 1011 0110 0011 1111 1111 1111,24,Odd,3x + 1,1011,2,1111,0
13,35831806,0000 0010 0010 0010 1011 1111 1111 1110,26,Even,>> 1,1000,0,1110,1
14,17915903,0000 0001 0001 0001 0101 1111 1111 1111,25,Odd,3x + 1,1000,1,1111,0
15,53747710,0000 0011 0011 0100 0001 1111 1111 1110,26,Even,>> 1,1100,0,1110,1
16,26873855,0000 0001 1001 1010 0000 1111 1111 1111,25,Odd,3x + 1,1100,2,1111,0
17,80621566,0000 0100 1100 1110 0010 1111 1111 1110,27,Even,>> 1,1001,0,1110,1
18,40310783,0000 0010 0110 0111 0001 0111 1111 1111,26,Odd,3x + 1,1001,1,1111,0
19,120932350,0000 0111 0011 0101 0100 0111 1111 1110,27,Even,>> 1,1110,0,1110,1
20,60466175,0000 0011 1001 1010 1010 0011 1111 1111,26,Odd,3x + 1,1110,2,1111,0
21,181398526,0000 1010 1100 1111 1110 1011 1111 1110,28,Even,>> 1,1010,0,1110,1
22,90699263,0000 0101 0110 0111 1111 0101 1111 1111,27,Odd,3x + 1,1010,2,1111,0
23,272097790,0001 0000 0011 0111 1110 0001 1111 1110,29,Even,>> 1,1000,0,1110,1
24,136048895,0000 1000 0001 1011 1111 0000 1111 1111,28,Odd,3x + 1,1000,1,1111,0
25,408146686,0001 1000 0101 0011 1101 0010 1111 1110,29,Even,>> 1,1100,0,1110,1
26,204073343,0000 1100 0010 1001 1110 1001 0111 1111,28,Odd,3x + 1,1100,2,1111,0
27,612220030,0010 0100 0111 1101 1011 1100 0111 1110,30,Even,>> 1,1001,0,1110,1
28,306110015,0001 0010 0011 1110 1101 1110 0011 1111,29,Odd,3x + 1,1001,1,1111,0
29,918330046,0011 0110 1011 1100 1001 1010 1011 1110,30,Even,>> 1,1101,0,1110,1
30,459165023,0001 1011 0101 1110 0100 1101 0101 1111,29,Odd,3x + 1,1101,2,1111,0
31,1377495070,0101 0010 0001 1010 1110 1000 0001 1110,31,Even,>> 1,1010,0,1110,1
32,688747535,0010 1001 0000 1101 0111 0100 0000 1111,30,Odd,3x + 1,1010,1,1111,0
33,2066242606,0111 1011 0010 1000 0101 1100 0010 1110,31,Even,>> 1,1111,0,1110,1
34,1033121303,0011 1101 1001 0100 0010 1110 0001 0111,30,Odd,3x + 1,1111,2,0111,0
35,3099363910,1011 1000 1011 1100 1000 1010 0100 0110,32,Even,>> 1,1011,0,0110,1
36,1549681955,0101 1100 0101 1110 0100 0101 0010 0011,31,Odd,3x + 1,1011,2,0011,0
37,4649045866,1000 1010 1000 1101 0110 0111 1011 0101 0,33,Even,>> 1,1000,0,1010,1
38,2324522933,1000 1010 1000 1101 0110 0111 1011 0101,32,Odd,3x + 1,1000,1,0101,0
39,6973568800,1100 1111 1101 0100 0001 1011 1001 0000 0,33,Even,>> 5,1100,0,0000,5
40,217924025,0000 1100 1111 1101 0100 0001 1011 1001,28,Odd,3x + 1,1100,2,1001,0
41,653772076,0010 0110 1111 0111 1100 0101 0010 1100,30,Even,>> 2,1001,0,1100,2
42,163443019,0000 1001 1011 1101 1111 0001 0100 1011,28,Odd,3x + 1,1001,1,1011,0
43,490329058,0001 1101 0011 1001 1101 0011 1110 0010,29,Even,>> 1,1110,0,0010,1
44,245164529,0000 1110 1001 1100 1110 1001 1111 0001,28,Odd,3x + 1,1110,2,0001,0
45,735493588,0010 1011 1101 0110 1011 1101 1101 0100,30,Even,>> 2,1010,0,0100,2
46,183873397,0000 1010 1111 0101 1010 1111 0111 0101,28,Odd,3x + 1,1010,2,0101,0
47,551620192,0010 0000 1110 0001 0000 1110 0110 0000,30,Even,>> 5,1000,0,0000,5
48,17238131,0000 0001 0000 0111 0000 1000 0111 0011,25,Odd,3x + 1,1000,1,0011,0
49,51714394,0000 0011 0001 0101 0001 1001 0101 1010,26,Even,>> 1,1100,0,1010,1
50,25857197,0000 0001 1000 1010 1000 1100 1010 1101,25,Odd,3x + 1,1100,2,1101,0
51,77571592,0000 0100 1001 1111 1010 0110 0000 1000,27,Even,>> 3,1001,0,1000,3
52,9696449,0000 0000 1001 0011 1111 0100 1100 0001,24,Odd,3x + 1,1001,1,0001,0
53,29089348,0000 0001 1011 1011 1101 1110 0100 0100,25,Even,>> 2,1101,0,0100,2
54,7272337,0000 0000 0110 1110 1111 0111 1001 0001,23,Odd,3x + 1,1101,2,0001,0
55,21817012,0000 0001 0100 1100 1110 0110 1011 0100,25,Even,>> 2,1010,0,0100,2
56,5454253,0000 0000 0101 0011 0011 1001 1010 1101,23,Odd,3x + 1,1010,1,1101,0
57,16362760,0000 0000 1111 1001 1010 1101 0000 1000,24,Even,>> 3,1111,0,1000,3
58,2045345,0000 0000 0001 1111 0011 0101 1010 0001,21,Odd,3x + 1,1111,2,0001,0
59,6136036,0000 0000 0101 1101 1010 0000 1110 0100,23,Even,>> 2,1011,0,0100,2
60,1534009,0000 0000 0001 0111 0110 1000 0011 1001,21,Odd,3x + 1,1011,2,1001,0
61,4602028,0000 0000 0100 0110 0011 1000 1010 1100,23,Even,>> 2,1000,0,1100,2
62,1150507,0000 0000 0001 0001 1000 1110 0010 1011,21,Odd,3x + 1,1000,1,1011,0
63,3451522,0000 0000 0011 0100 1010 1010 1000 0010,22,Even,>> 1,1101,0,0010,1
64,1725761,0000 0000 0001 1010 0101 0101 0100 0001,21,Odd,3x + 1,1101,2,0001,0
65,5177284,0000 0000 0100 1110 1111 1111 1100 0100,23,Even,>> 2,1001,0,0100,2
66,1294321,0000 0000 0001 0011 1011 1111 1111 0001,21,Odd,3x + 1,1001,1,0001,0
67,3882964,0000 0000 0011 1011 0011 1111 1101 0100,22,Even,>> 2,1110,0,0100,2
68,970741,0000 0000 0000 1110 1100 1111 1111 0101,20,Odd,3x + 1,1110,2,0101,0
69,2912224,0000 0000 0010 1100 0110 1111 1110 0000,22,Even,>> 5,1011,0,0000,5
70,91007,0000 0000 0000 0001 0110 0011 0111 1111,17,Odd,3x + 1,1011,2,1111,0
71,273022,0000 0000 0000 0100 0010 1010 0111 1110,19,Even,>> 1,1000,0,1110,1
72,136511,0000 0000 0000 0010 0001 0101 0011 1111,18,Odd,3x + 1,1000,1,1111,0
73,409534,0000 0000 0000 0110 0011 1111 1011 1110,19,Even,>> 1,1100,0,1110,1
74,204767,0000 0000 0000 0011 0001 1111 1101 1111,18,Odd,3x + 1,1100,2,1111,0
75,614302,0000 0000 0000 1001 0101 1111 1001 1110,20,Even,>> 1,1001,0,1110,1
76,307151,0000 0000 0000 0100 1010 1111 1100 1111,19,Odd,3x + 1,1001,1,1111,0
77,921454,0000 0000 0000 1110 0000 1111 0110 1110,20,Even,>> 1,1110,0,1110,1
78,460727,0000 0000 0000 0111 0000 0111 1011 0111,19,Odd,3x + 1,1110,2,0111,0
79,1382182,0000 0000 0001 0101 0001 0111 0010 0110,21,Even,>> 1,1010,0,0110,1
80,691091,0000 0000 0000 1010 1000 1011 1001 0011,20,Odd,3x + 1,1010,1,0011,0
81,2073274,0000 0000 0001 1111 1010 0010 1011 1010,21,Even,>> 1,1111,0,1010,1
82,1036637,0000 0000 0000 1111 1101 0001 0101 1101,20,Odd,3x + 1,1111,2,1101,0
83,3109912,0000 0000 0010 1111 0111 0100 0001 1000,22,Even,>> 3,1011,0,1000,3
84,388739,0000 0000 0000 0101 1110 1110 1000 0011,19,Odd,3x + 1,1011,2,0011,0
85,1166218,0000 0000 0001 0001 1100 1011 1000 1010,21,Even,>> 1,1000,0,1010,1
86,583109,0000 0000 0000 1000 1110 0101 1100 0101,20,Odd,3x + 1,1000,1,0101,0
87,1749328,0000 0000 0001 1010 1011 0001 0101 0000,21,Even,>> 4,1101,0,0000,4
88,109333,0000 0000 0000 0001 1010 1011 0001 0101,17,Odd,3x + 1,1101,2,0101,0
89,328000,0000 0000 0000 0101 0000 0001 0100 0000,19,Even,>> 6,1010,0,0000,6
90,5125,0000 0000 0000 0000 0001 0100 0000 0101,13,Odd,3x + 1,1010,1,0101,0
91,15376,0000 0000 0000 0000 0011 1100 0001 0000,14,Even,>> 4,1111,0,0000,4
92,961,0000 0000 0000 0000 0000 0011 1100 0001,10,Odd,3x + 1,1111,2,0001,0
93,2884,0000 0000 0000 0000 0000 1011 0100 0100,12,Even,>> 2,1011,0,0100,2
94,721,0000 0000 0000 0000 0000 0010 1101 0001,10,Odd,3x + 1,1011,2,0001,0
95,2164,0000 0000 0000 0000 0000 1000 0111 0100,12,Even,>> 2,1000,0,0100,2
96,541,0000 0000 0000 0000 0000 0010 0001 1101,10,Odd,3x + 1,1000,1,1101,0
97,1624,0000 0000 0000 0000 0000 0110 0101 1000,11,Even,>> 3,1100,0,1000,3
98,203,0000 0000 0000 0000 0000 0000 1100 1011,8,Odd,3x + 1,1100,2,1011,0
99,610,0000 0000 0000 0000 0000 0010 0110 0010,10,Even,>> 1,1001,0,0010,1
100,305,0000 0000 0000 0000 0000 0001 0011 0001,9,Odd,3x + 1,1001,1,0001,0
101,916,0000 0000 0000 0000 0000 0011 1001 0100,10,Even,>> 2,1110,0,0100,2
102,229,0000 0000 0000 0000 0000 0000 1110 0101,8,Odd,3x + 1,1110,2,0101,0
103,688,0000 0000 0000 0000 0000 0010 1011 0000,10,Even,>> 4,1010,0,0000,4
104,43,0000 0000 0000 0000 0000 0000 0010 1011,6,Odd,3x + 1,1010,2,1011,0
105,130,0000 0000 0000 0000 0000 0000 1000 0010,8,Even,>> 1,1000,0,0010,1
106,65,0000 0000 0000 0000 0000 0000 0100 0001,7,Odd,3x + 1,1000,1,0001,0
107,196,0000 0000 0000 0000 0000 0000 1100 0100,8,Even,>> 2,1100,0,0100,2
108,49,0000 0000 0000 0000 0000 0000 0011 0001,6,Odd,3x + 1,1100,2,0001,0
109,148,0000 0000 0000 0000 0000 0000 1001 0100,8,Even,>> 2,1001,0,0100,2
110,37,0000 0000 0000 0000 0000 0000 0010 0101,6,Odd,3x + 1,1001,1,0101,0
111,112,0000 0000 0000 0000 0000 0000 0111 0000,7,Even,>> 4,1110,0,0000,4
112,7,0000 0000 0000 0000 0000 0000 0000 0111,3,Odd,3x + 1,0111,2,0111,0
113,22,0000 0000 0000 0000 0000 0000 0001 0110,5,Even,>> 1,1011,0,0110,1
114,11,0000 0000 0000 0000 0000 0000 0000 1011,4,Odd,3x + 1,1011,2,1011,0
115,34,0000 0000 0000 0000 0000 0000 0010 0010,6,Even,>> 1,1000,0,0010,1
116,17,0000 0000 0000 0000 0000 0000 0001 0001,5,Odd,3x + 1,1000,1,0001,0
117,52,0000 0000 0000 0000 0000 0000 0011 0100,6,Even,>> 2,1101,0,0100,2
118,13,0000 0000 0000 0000 0000 0000 0000 1101,4,Odd,3x + 1,1101,2,1101,0
119,40,0000 0000 0000 0000 0000 0000 0010 1000,6,Even,>> 3,1010,0,1000,3
120,5,0000 0000 0000 0000 0000 0000 0000 0101,3,Odd,3x + 1,0101,2,0101,0
121,16,0000 0000 0000 0000 0000 0000 0001 0000,5,Even,>> 4,1000,0,0000,4
122,1,0000 0000 0000 0000 0000 0000 0000 0001,1,Odd,,0001,0,0001,0

Number of iterations: 123