In [4]:
import pandas as pd
from IPython.display import display

def format_binary_nibbles(binary_str, num_nibbles=8):
    binary_str = binary_str.zfill(num_nibbles * 4)
    return ' '.join(binary_str[i:i+4] for i in range(0, len(binary_str), 4))

def collatz_sequence_with_operations(n):
    seq = []
    odd_even = []
    operations = []
    growth_strength = []
    collapse_strength = []
    msbs = []
    lsbs = []
    bit_counts = []
    
    iteration_count = 0  # Counter to track the number of iterations
    
    while True:
        iteration_count += 1
        
        binary_n = bin(n)[2:]
        seq.append(n)
        odd_even.append('Even' if n % 2 == 0 else 'Odd')
        msbs.append(format_binary_nibbles(binary_n[:4], num_nibbles=1))
        lsbs.append(format_binary_nibbles(binary_n[-4:], num_nibbles=1))
        bit_counts.append(len(binary_n))
        if n == 1:
            operations.append('')
            growth_strength.append(0)
            collapse_strength.append(0)
            break
        prev_num_bits = len(binary_n)
        if n % 2 == 0:
            shift_count = 0
            while n % 2 == 0:
                n //= 2
                shift_count += 1
            operations.append(f'>> {shift_count}')
            growth_strength.append(0)
            collapse_strength.append(shift_count)
        else:
            n = 3 * n + 1
            operations.append('3x + 1')
            growth_strength.append(len(bin(n)[2:]) - prev_num_bits)
            collapse_strength.append(0)
    
    df = pd.DataFrame({
        'Decimal': seq,
        'Binary': [format_binary_nibbles(bin(num)[2:]) for num in seq],
        'Bit Count': bit_counts,
        'Odd/Even': odd_even,
        'Operation': operations,
        '4 MSBs': msbs,
        'Growth Strength': growth_strength,
        '4 LSBs': lsbs,
        'Collapse Strength': collapse_strength
    })
    
    return df, iteration_count

# Set the display option to show all rows
pd.set_option('display.max_rows', None)

# Specify the binary input
binary_input = "1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110 1110"
binary_input = "10001"

# Remove spaces from the binary input
binary_input = binary_input.replace(" ", "")

# Convert the binary input to decimal
decimal_input = int(binary_input, 2)

# Execute the Collatz sequence for the input number
print(f"Collatz sequence for {binary_input}:")
df, num_iterations = collatz_sequence_with_operations(decimal_input)
display(df)

# Report the number of iterations
print(f"Number of iterations: {num_iterations}")

Collatz sequence for 10001:

,Decimal,Binary,Bit Count,Odd/Even,Operation,4 MSBs,Growth Strength,4 LSBs,Collapse Strength
0,17,0000 0000 0000 0000 0000 0000 0001 0001,5,Odd,3x + 1,1000,1,0001,0
1,52,0000 0000 0000 0000 0000 0000 0011 0100,6,Even,>> 2,1101,0,0100,2
2,13,0000 0000 0000 0000 0000 0000 0000 1101,4,Odd,3x + 1,1101,2,1101,0
3,40,0000 0000 0000 0000 0000 0000 0010 1000,6,Even,>> 3,1010,0,1000,3
4,5,0000 0000 0000 0000 0000 0000 0000 0101,3,Odd,3x + 1,0101,2,0101,0
5,16,0000 0000 0000 0000 0000 0000 0001 0000,5,Even,>> 4,1000,0,0000,4
6,1,0000 0000 0000 0000 0000 0000 0000 0001,1,Odd,,0001,0,0001,0

Number of iterations: 7